# -*- coding: utf-8 -*-
"""python_basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GijUTNU8VCDU-rGlxDiIbu5PJdTtzYGb
"""

print("Hello World")

a = 20;
if a > 15:
  print("Pass")
else:
  print("Fail")

name = "Achala"
age = 26
height = 168.2
is_Active = True

print(type(name))
print(type(age))
print(type(height))
print(type(is_Active))

fruits = ["Apple", "Mango", "Cherries"]   #List

student = {                               #dictionary
    "name ": "Achala",
    "age" : 26,
    "height" : 168.2
}

colors = ("Red", "Blue", "Green")         #tuple

numbers = {1, 2, 3 }                      #set

for x in fruits:
  print(x)

print()
for x in colors:
  print(x)

print()
for x in numbers:
  print(x)

print()
for x in colors:
  print(x)

print()
for x in student:
  print(x)

name = input("Enter your name: ")
print("Hello", name)

age = int(input("Enter age: "))
print("Your age is ", age)

for i in range(5):
    print(i)

count = 1

while count <= 5:
    print(count)
    count += 1

def greet():
    print("Hello")

greet()

def greet(name):
    print("Hello", name)

greet("Achala")

def add(a, b):
    return a + b

result = add(5, 3)
print(result)

numbers = [10, 20, 30]

numbers.append(40)

print(numbers[0])
print(len(numbers))

for num in numbers:
    print(num)

student = {
    "name": "Achala",
    "age": 22
}

print(student["name"])

from math import sqrt

print(sqrt(25))

def calculate_average(marks):
    total = 0

    for mark in marks:
        total += mark

    return total / len(marks)

marks = [80, 75, 90, 85]

avg = calculate_average(marks)

print("Average:", avg)